// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// Stubbed by commit application: obsolete migration designer replaced to avoid overrides.
using Microsoft.EntityFrameworkCore;

namespace SkillShare.Migrations
{
    partial class Createtables
    {
        // intentionally empty
    }
}
